apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: sandbox
spec:
  type: ClusterIP
  selector:
    app: techtrends
  ports:
    - name: http
      port: 4111
      targetPort: 3111
      protocol: TCP

