namespace: 
   name: sandbox

image:
   repository: techtrends
   tag: main
   PullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi
  ports:
    - containerPort: 4111         
  livenessProbe:
    httpGet:
        path: /healthz
        port: 3111
  readinessProbe:
      httpGet:
        path: /healthz
        port: 3111
